- name: 컨테이너런타임 설치를 위한 패키지 설치
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
  when: ansible_distribution == 'CentOS'
  tags:
    - centos

- name: Docker 패키지 레포지토리 추가
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  when: ansible_distribution == 'CentOS'
  tags:
    - repo
    - centos

- name: 기본 패키지 설치
  yum:
    name:
      - containerd
      - iproute-tc
    state: present

- name: Docker 패키지 설치 (CentOS)
  yum:
    name:
      - docker-ce
      - docker-ce-cli
    state: present
  when: ansible_distribution == 'CentOS' and kube_container_runtime == 'docker'
  tags:
    - docker
    - pkg
    - "docker-pkg"
    - centos

- name: Docker 패키지 설치 (Amazon)
  command: amazon-linux-extras install docker -y
  when: ansible_distribution == 'Amazon' and kube_container_runtime == 'docker'
  tags:
    - docker
    - pkg
    - "docker-pkg"
    - amazon

- name: Docker 데몬 설정
  copy:
    src: files/docker_daemon.json
    dest: /etc/docker/daemon.json
  notify:
    - systemd 데몬 리로드
    - Docker 서비스 enable
  when: kube_container_runtime == 'docker'
  tags:
    - docker
    - config

- name: containerd 설정
  copy:
    src: files/config.toml
    dest: /etc/containerd/config.toml
  when: kube_container_runtime == 'containerd'
  tags:
    - containerd
    - config
