- name: Kubernetes 패키지 레포지토리 추가
  yum_repository:
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    name: kubernetes
    description: kubernetes
    enabled: true
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    exclude:
      - kubelet
      - kubeadm
      - kubectl
  tags:
    - repo

- name: kubeadm, kubelet, kubectl 패키지 설치
  yum:
    name:
      - kubelet-{{ kube_version }}
      - kubeadm-{{ kube_version }}
      - kubectl-{{ kube_version }}
    disable_excludes: kubernetes
    state: present
  notify:
    - systemd 데몬 리로드
    - 서비스 enable
  tags:
    - pkg
    - "k8s-pkg"
