- name: ipvs - 커널 모듈 로드
  copy:
    src: files/module_ipvs.conf
    dest: /etc/modules-load.d/ipvs.conf
  when: ansible_distribution == 'Amazon' and kube_proxy_mode == 'ipvs'
  tags:
    - config
    - ipvs
    - amazon

- name: ipvs - 패키지 설치
  yum:
    name:
      - ipset
      - ipvsadm
    state: present
  when: ansible_distribution == 'Amazon' and kube_proxy_mode == 'ipvs'
  tags:
    - config
    - ipvs
    - amazon

- name: 커널 모듈 로드
  copy:
    src: files/module_{{ kube_container_runtime }}.conf
    dest: /etc/modules-load.d/k8s.conf
  tags:
    - config

- name: sysctl 구성
  copy:
    src: files/sysctl_k8s.conf
    dest: /etc/sysctl.d/k8s.conf
  notify: sysctl 리로드
  tags:
    - config

- name: modprobe
  shell: |
    modprobe overlay
    modprobe br_netfilter
    sysctl --system

- name: CentOS 기본 설정
  script: files/setting_centos.sh
  when: ansible_distribution == 'CentOS'
  tags:
    - centos

- name: 컨테이너런타임 설치를 위한 패키지 설치
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
  when: ansible_distribution == 'CentOS'
  tags:
    - centos

- name: Docker 패키지 레포지토리 추가
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  when: ansible_distribution == 'CentOS'
  tags:
    - repo
    - centos

- name: Kubernetes 패키지 레포지토리 추가
  yum_repository:
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    name: kubernetes
    description: kubernetes
    enabled: true
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    exclude:
      - kubelet
      - kubeadm
      - kubectl
  tags:
    - repo

- name: 기본 패키지 설치
  yum:
    name:
      - containerd
      - iproute-tc
    state: present

- name: Docker 패키지 설치 (CentOS)
  yum:
    name:
      - docker-ce
      - docker-ce-cli
    state: present
  when: ansible_distribution == 'CentOS' and kube_container_runtime == 'docker'
  tags:
    - docker
    - pkg
    - centos

- name: Docker 패키지 설치 (Amazon)
  command: amazon-linux-extras install docker -y
  when: ansible_distribution == 'Amazon' and kube_container_runtime == 'docker'
  tags:
    - docker
    - pkg
    - amazon

- name: Docker 데몬 설정
  copy:
    src: files/docker_daemon.json
    dest: /etc/docker/daemon.json
  notify:
    - systemd 데몬 리로드
    - Docker 서비스 enable
  when: kube_container_runtime == 'docker'
  tags:
    - docker
    - config

- name: containerd 설정
  copy:
    src: files/config.toml
    dest: /etc/containerd/config.toml
  when: kube_container_runtime == 'containerd'
  tags:
    - containerd
    - config

- name: kubeadm, kubelet, kubectl 패키지 설치
  yum:
    name:
      - kubelet-{{ kube_version }}
      - kubeadm-{{ kube_version }}
      - kubectl-{{ kube_version }}
    disable_excludes: kubernetes
    state: present
  notify:
    - systemd 데몬 리로드
    - 서비스 enable
  tags:
    - pkg
