- name: yum install pkg
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ pkg }}"
  tags:
    - "pkg"

- name: 서비스 enable
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ svc }}"

- name: 타임존 설정
  timezone:
    name: Asia/Seoul

- name: /etc/hosts에 자기 hostname 추가 (kubeadm init 관련)
  lineinfile:
    path: "/etc/hosts"
    line: "127.0.0.1 {{ ansible_hostname }}"
    state: present
